# Generated by Django 2.1.5 on 2019-02-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryweb', '0005_auto_20190203_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
