# Generated by Django 2.1.5 on 2019-02-04 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('galleryweb', '0006_auto_20190203_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='autor',
            field=models.CharField(default='Nicolas', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multimedia',
            name='ciudad',
            field=models.CharField(default='Bogotá', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multimedia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multimedia',
            name='pais',
            field=models.CharField(default='Colombia', max_length=200),
            preserve_default=False,
        ),
    ]
