# Generated by Django 2.1.5 on 2019-02-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleryweb', '0002_auto_20190203_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('archivoImagen', models.ImageField(blank=True, null=True, upload_to='files')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryweb.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMultimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='imageFile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryweb.TipoMultimedia'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryweb.Usuario'),
        ),
        migrations.AddField(
            model_name='clip',
            name='multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryweb.Multimedia'),
        ),
        migrations.AddField(
            model_name='clip',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleryweb.Usuario'),
        ),
    ]
