# Generated by Django 2.1.5 on 2019-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryweb', '0003_auto_20190203_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='info',
            field=models.CharField(default='Descrpcion de llenado para las que ya estaban', max_length=1000),
            preserve_default=False,
        ),
    ]
